namespace PackageInstallerExercise {
  /// <summary>
  /// Types of return values that could be generated by the program
  /// </summary>
  public enum ConsoleReturnTypes {
    Success = 0,
    NoArguments = 1,
    TooManyArguments = 2
  }
}
